### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by aforren1** [aforren1/deploying-psychopy#1]
- [ ] Extra pruning (unused imports)
- [ ] Writeup
- [ ] Exe signing? (not possible w/o buying a cert)
- [ ] Data transfer options?
